sonar.projectKey=ximemolina_taglib-sec-analysis
sonar.organization=ximemolina
sonar.sources=.
sonar.inclusions=taglib/ogg/oggpageheader.cpp,\
taglib/ogg/xiphcomment.cpp,\
taglib/asf/asffile.cpp,\
taglib/dsdiff/dsdifffile.cpp,\
taglib/it/itfile.cpp,\
taglib/s3m/s3mfile.cpp,\
taglib/mod/modfile.cpp
